language: java
sudo: false

jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk7
  - openjdk6

install: "mvn install -DskipTests=true -Dinvoker.skip=true -B"

script: "mvn test integration-test -B"

after_success:
  - chmod -R 777 ./travis/after_success.sh
  - ./travis/after_success.sh

after_failure: "cat /home/travis/build/mybatis/migrations-maven-plugin/target/it/migration-plugin-*/build.log"

env:
  global:
    - secure: "BUC/SL8XomyhtNP6/1Fulhqo5We2yVvwhwU4dqSBx5qUWgOEagQBZpINKzkK\nk8f9A0XzpXzJoJuvlHqdkGU8U0EuDKA7QfK/GdHY1Jc8Gbkq3NvzZ9hTbdKS\nJqrQoOfSx63zpVuw702vFf9rCtKyRGcFa3YhZiqb2qYWtOe7pe4="
    - secure: "JxjpKvLX+ekQxgcPHyYKZUNJcSAd7zgOkhH4Qkkc2c1zgJPkERGumwkMx8P/\nlyYEJ26vEsRcp4ZCiyWsmN5qaClyNDTXiP659ZG4mgcCHxp0dLRlUuYc2dGb\nnKRdKefauEaI+yaQQ6EVGGBi/uDaUldx6bUXvZ6G4kvB1WwWng8="
